// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentInternshipMgmt.Infrastructure.Persistence;

#nullable disable

namespace StudentInternshipMgmt.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001021843_AddJobPositionListFields")]
    partial class AddJobPositionListFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentInternshipMgmt.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactPosition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Companies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Nguyen Van Linh, Quan 7, TP.HCM",
                            ContactPerson = "Nguyen Van A",
                            Industry = "Phat trien phan mem",
                            Name = "Cong ty TNHH Giai phap Phan mem ABC"
                        },
                        new
                        {
                            Id = 2,
                            Address = "45 Le Loi, Quan 1, TP.HCM",
                            ContactPerson = "Tran Thi B",
                            Industry = "Cong nghe thong tin",
                            Name = "Cong ty Co phan Cong nghe XYZ"
                        },
                        new
                        {
                            Id = 3,
                            Address = "78 Vo Van Ngan, TP. Thu Duc, TP.HCM",
                            ContactPerson = "Le Van C",
                            Industry = "Dich vu so / Du lieu",
                            Name = "Cong ty TNHH Dich vu So Delta"
                        });
                });

            modelBuilder.Entity("StudentInternshipMgmt.Domain.Entities.JobPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("date");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("JobPositions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            Deadline = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Phòng Công nghệ",
                            Description = "Thuc tap phat trien API voi ASP.NET Core va Entity Framework Core.",
                            IsOpen = true,
                            Quantity = 3,
                            Title = "Thuc tap sinh Lap trinh vien .NET"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            Deadline = new DateTime(2026, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Phòng Kiểm thử",
                            Description = "Thuc tap kiem thu chuc nang va viet test case.",
                            IsOpen = true,
                            Quantity = 2,
                            Title = "Thuc tap sinh Kiem thu phan mem (Tester)"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 2,
                            Deadline = new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Phòng Thiết kế",
                            Description = "Thuc tap xay dung giao dien nguoi dung voi ReactJS.",
                            IsOpen = true,
                            Quantity = 2,
                            Title = "Thuc tap sinh Frontend ReactJS"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 3,
                            Department = "Phòng Dữ liệu",
                            Description = "Thuc tap xu ly va truc quan hoa du lieu.",
                            IsOpen = false,
                            Quantity = 1,
                            Title = "Thuc tap sinh Phan tich du lieu"
                        },
                        new
                        {
                            Id = 1001,
                            CompanyId = 2,
                            Deadline = new DateTime(2026, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Phòng Dữ liệu",
                            Description = "Hỗ trợ làm sạch dữ liệu và xây dựng báo cáo trực quan.",
                            IsOpen = true,
                            Location = "Tòa nhà Công nghệ, Quận 3, TP.HCM",
                            Quantity = 2,
                            Title = "Thực tập sinh Phân tích dữ liệu"
                        },
                        new
                        {
                            Id = 1002,
                            CompanyId = 3,
                            Department = "Phòng Thiết kế",
                            Description = "Tham gia thiết kế trải nghiệm và giao diện sản phẩm số.",
                            IsOpen = true,
                            Quantity = 1,
                            Title = "Thực tập sinh Thiết kế sản phẩm"
                        },
                        new
                        {
                            Id = 1003,
                            CompanyId = 1,
                            Deadline = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Phòng Kiểm thử",
                            Description = "Viết và thực thi kịch bản kiểm thử cho sản phẩm.",
                            IsOpen = false,
                            Quantity = 2,
                            Title = "Thực tập sinh Kiểm thử phần mềm"
                        },
                        new
                        {
                            Id = 1004,
                            CompanyId = 3,
                            Deadline = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Phòng Công nghệ",
                            Description = "Phát triển dịch vụ web với ASP.NET Core.",
                            IsOpen = true,
                            Quantity = 3,
                            Title = "Thực tập sinh Phát triển .NET"
                        });
                });

            modelBuilder.Entity("StudentInternshipMgmt.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReadBy")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsRead", "CreatedAt");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("StudentInternshipMgmt.Domain.Entities.PlacementRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("JobPositionId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("JobPositionId");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("StudentId");

                    b.ToTable("PlacementRequests", (string)null);
                });

            modelBuilder.Entity("StudentInternshipMgmt.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_Token");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("StudentInternshipMgmt.Domain.Entities.StatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangedBy")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("CompanyId");

                    b.HasIndex("StudentId");

                    b.ToTable("StatusHistories", (string)null);
                });

            modelBuilder.Entity("StudentInternshipMgmt.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("JobPositionId")
                        .HasColumnType("int");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("JobPositionId");

                    b.HasIndex("StudentCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Students_StudentCode")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("StudentInternshipMgmt.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_StudentId")
                        .HasFilter("[StudentId] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MustChangePassword = false,
                            PasswordHash = "$2b$11$1zB61f0oX7e98EaZGDvS8OVQumC4VlWWMXlU/yXz7v8q.Pe.dy9QW",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("StudentInternshipMgmt.Domain.Entities.JobPosition", b =>
                {
                    b.HasOne("StudentInternshipMgmt.Domain.Entities.Company", "Company")
                        .WithMany("JobPositions")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("StudentInternshipMgmt.Domain.Entities.PlacementRequest", b =>
                {
                    b.HasOne("StudentInternshipMgmt.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentInternshipMgmt.Domain.Entities.JobPosition", "JobPosition")
                        .WithMany()
                        .HasForeignKey("JobPositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudentInternshipMgmt.Domain.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudentInternshipMgmt.Domain.Entities.Student", "Student")
                        .WithMany("PlacementRequests")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("JobPosition");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentInternshipMgmt.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("StudentInternshipMgmt.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudentInternshipMgmt.Domain.Entities.StatusHistory", b =>
                {
                    b.HasOne("StudentInternshipMgmt.Domain.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentInternshipMgmt.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudentInternshipMgmt.Domain.Entities.Student", "Student")
                        .WithMany("StatusHistories")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Company");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentInternshipMgmt.Domain.Entities.Student", b =>
                {
                    b.HasOne("StudentInternshipMgmt.Domain.Entities.Company", "Company")
                        .WithMany("Students")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudentInternshipMgmt.Domain.Entities.JobPosition", "JobPosition")
                        .WithMany("Students")
                        .HasForeignKey("JobPositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("JobPosition");
                });

            modelBuilder.Entity("StudentInternshipMgmt.Domain.Entities.User", b =>
                {
                    b.HasOne("StudentInternshipMgmt.Domain.Entities.Student", "Student")
                        .WithOne("User")
                        .HasForeignKey("StudentInternshipMgmt.Domain.Entities.User", "StudentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentInternshipMgmt.Domain.Entities.Company", b =>
                {
                    b.Navigation("JobPositions");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentInternshipMgmt.Domain.Entities.JobPosition", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentInternshipMgmt.Domain.Entities.Student", b =>
                {
                    b.Navigation("PlacementRequests");

                    b.Navigation("StatusHistories");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudentInternshipMgmt.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
